version: '3.9'

services:
  dm-api-gateway:
    networks:
      - dm-energy-consumption
      - dm-users-service
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: bash -c "poetry run python src/main.py"
    container_name: dm-api-gateway
    volumes:
      - .:/dm-api-gateway
    ports:
      - "8100:8100"
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M

networks:
  dm-energy-consumption:
    external: true
  dm-users-service:
    external: true
