version: '3.9'

services:
  dm-api-gateway:
    networks:
      - dm-energy-consumption
      - dm-users-service
      - dm-devices
      - dm-payments
      - dm-water-consumption
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: bash -c "poetry run python src/main.py"
    container_name: dm-api-gateway
    volumes:
      - .:/dm-api-gateway
    ports:
      - "8000:8000"

networks:
  dm-energy-consumption:
    external: true
  dm-users-service:
    external: true
  dm-water-consumption:
    external: true
  dm-payments:
    external: true
  dm-devices:
    external: true
